In [1]:
import pandas as pd 
import numpy as np
# Đọc dữ liệu đầu vào 
dataPath = 'Data_Gestational_diabetes.csv'

In [2]:
# Dữ liệu đầu vào bao gồm 23 đặc trưng và đặc trưng thứ 23 là nhãn (0 - Bình Thường, 1 - Mắc ĐTD)

In [3]:
#tenCot = ['Tuoi','NN','TrinhDo','TuoiThai','SoLanMT','Para','TieuSu',' TienSuGD','ChieuCao','CanNang1','CanNang2','HuyetAp1','HuyetAp2','TinhChatCV1','TinhChatCV2','DinhDuong','TheThao1','TheThao2','TheThao3', 
#'Glucose1','Glucose2','Glucose3','KetLuan'] 
columnName = ['Year_old','Occupatio','Education','gestational_age','Number_of_pregnancy','Para','Childbirth_history', 
              'Family_history','Height','Pre_gregnancy_weight','Current_Weight','Upper_blood_pressure', 
              'Lower_blood_pressure','Work_status','Work_performance','Nutrition', 'Sport_practice_day_per_month',
              'Sport_day_per_week', 'Sport_last_month', 'Glucose1','Glucose2','Glucose3','Conclude']

In [4]:
dataGD = pd.read_csv(dataPath, names= columnName)
print('In ra 10 bản ghi đầu tiên')

# Chuyển dữ liệu đầu vào sang dạng Ma trận 
dataMatrix = dataGD.values 
# Lấy ra các đặc trưng  
X = dataMatrix[1:,:-1]
# Lấy nhãn chẩn đoán: 0 - Bình Thường, 1 - Mắc ĐTD 
y = dataMatrix[1:,-1]
dataGD.head(10)

In ra 5 bản ghi đầu tiên

,Year_old,Occupatio,Education,gestational_age,Number_of_pregnancy,Para,Childbirth_history,Family_history,Height,Pre_gregnancy_weight,...,Work_status,Work_performance,Nutrition,Sport_practice_day_per_month,Sport_day_per_week,Sport_last_month,Glucose1,Glucose2,Glucose3,Conclude
0,Year_old,Occupatio,Education,gestational_age,Number_of_pregnancy,Para,Childbirth_history,Family_history,Height,Pre_gregnancy_weight,...,Work_status,Work_performance,Nutrition,Sport_practice_day_per_month,Sport_day_per_week,Sport_last_month,Glucose1,Glucose2,Glucose3,Conclude
1,35,2,3,24,2,2,1,0,1.54,52,...,1,0,2,1,2,30,4.37,9.68,7.52,2
2,39,0,0,24,1,0,0,0,1.57,41,...,1,0,2,1,2,40,4.05,8.31,7.39,0
3,31,3,2,24,1,0,0,0,1.58,47,...,1,0,2,1,3,15,4.43,8.06,6.75,0
4,31,0,1,24,2,3,0,0,1.6,45,...,1,0,2,0,0,0,4.58,10.36,10.38,1
5,26,2,2,24,2,2,0,0,1.58,47,...,1,0,2,0,0,0,3.7,6.8,5.79,0
6,24,3,2,24,1,0,0,0,1.62,49,...,1,0,2,0,0,0,4,8.72,7.05,0
7,31,0,0,24,1,0,0,1,1.57,45,...,2,0,2,0,0,0,5.22,8.75,8.12,2
8,28,4,3,24,1,0,0,1,1.6,43,...,1,0,2,1,3,30,3.59,7.75,3.08,0
9,27,3,3,24,1,0,0,0,1.49,45,...,1,0,2,1,2,30,3.8,7.69,6.47,0

In [5]:
from sklearn import model_selection 
n_splits = 10 
# chia tập dữ liệu thành n_splits phần giống nhau 
kfold = model_selection.KFold(n_splits = n_splits,shuffle =True, random_state=7)

In [6]:
from sklearn import svm 
from sklearn.model_selection import GridSearchCV 
from sklearn.svm import SVC 
import numpy as np 
# Lựa chọn tham số C, gama tối ưu cho mô hình SVM, với kernel là 'rbf' 
param_grid = {'C': np.logspace(-2, 10, 13), 'gamma': np.logspace(-9, 3, 13),'kernel': ['rbf']} 
# Sử dụng lưới tìm kiếm để xác định tham số tối ưu cho mô hình SVM 
grid = GridSearchCV(SVC(), param_grid=param_grid, cv=kfold) 
grid.fit(X, y) 
print("Tham số tốt nhất là %s với độ chính xác trung bình %0.4f"% (grid.best_params_, grid.best_score_))

Tham số tốt nhất là {'C': 100000.0, 'gamma': 1e-06, 'kernel': 'rbf'} với độ chính xác trung bình 0.8820

In [7]:
X

array([['35', '2', '3', ..., '4.37', '9.68', '7.52'],
       ['39', '0', '0', ..., '4.05', '8.31', '7.39'],
       ['31', '3', '2', ..., '4.43', '8.06', '6.75'],
       ...,
       ['30', '15', '3', ..., '4.52', '7.6', '6.42'],
       ['24', '0', '1', ..., '4.48', '6.11', '5.97'],
       ['29', '0', '1', ..., '4.33', '8.3', '7.92']], dtype=object)

In [10]:
y_hat= grid.predict(X)

In [15]:
from sklearn.metrics import confusion_matrix, classification_report

In [13]:
confusion_matrix(y, y_hat)

array([[918,  16,   0],
       [ 33, 215,   0],
       [ 78,  20,   0]])

In [17]:
print(classification_report(y, y_hat))

              precision    recall  f1-score   support

           0       0.89      0.98      0.94       934
           1       0.86      0.87      0.86       248
           2       0.00      0.00      0.00        98

    accuracy                           0.89      1280
   macro avg       0.58      0.62      0.60      1280
weighted avg       0.82      0.89      0.85      1280